services:
  - type: web
    name: questionnaire-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://questionnaire-backend.onrender.com

  - type: web
    name: questionnaire-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      alembic upgrade head
    startCommand: cd backend && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: questionnaire-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://questionnaire-frontend.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

databases:
  - name: questionnaire-db
    databaseName: questionnaire
    plan: free
    ipAllowList: []
